# Generated by Django 2.0.6 on 2018-06-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
